version: "3.9"

services:
  backend:
    build: .
    container_name: backend-agent
    ports:
      - "8000:8000"
    volumes:
      - ./backend/chroma_db:/app/backend/chroma_db
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
